=== io7m-com/looseleaf/com.io7m.looseleaf.server.api/src/main/resources/com/io7m/looseleaf/server/api/looseleaf-config-1.schema.json
{
  "$id": "https://www.io7m.com/software/looseleaf/looseleaf-config-1.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",

  "$defs": {
    "SchemaIdentifier": {
      "type": "string",
      "const": "https://www.io7m.com/software/looseleaf/looseleaf-config-1.json"
    },

    "BindAddress": {
      "type": "object",
      "properties": {
        "host": {
          "type": "string"
        },
        "port": {
          "type": "number"
        }
      },
      "additionalProperties": false,
      "required": [
        "host",
        "port"
      ]
    },

    "Action": {
      "type": "string",
      "enum": [
        "READ",
        "WRITE"
      ]
    },

    "Grant": {
      "type": "object",
      "properties": {
        "action": {
          "$ref": "#/$defs/Action"
        },
        "keys": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "required": [
        "action",
        "keys"
      ]
    },

    "Role": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "grants": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/Grant"
          }
        }
      },
      "additionalProperties": false,
      "required": [
        "name",
        "grants"
      ]
    },

    "Password": {
      "type": "object",
      "properties": {
        "algorithm": {
          "type": "string"
        },
        "hash": {
          "type": "string",
          "format": "[A-F0-9]+"
        },
        "salt": {
          "type": "string",
          "format": "[A-F0-9]+"
        }
      },
      "additionalProperties": false,
      "required": [
        "algorithm",
        "hash",
        "salt"
      ]
    },

    "User": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "password": {
          "$ref": "#/$defs/Password"
        },
        "roles": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "additionalProperties": false,
      "required": [
        "name",
        "password",
        "roles"
      ]
    },

    "Configuration": {
      "type": "object",
      "properties": {
        "%schema": {
          "$ref": "#/$defs/SchemaIdentifier"
        },
        "addresses": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/BindAddress"
          }
        },
        "databaseFile": {
          "type": "string"
        },
        "roles": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/Role"
          }
        },
        "users": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/User"
          }
        }
      },
      "additionalProperties": false,
      "required": [
        "%schema",
        "addresses",
        "databaseFile",
        "roles",
        "users"
      ]
    }
  },

  "$ref": "#/$defs/Configuration"
}

=== io7m-com/looseleaf/com.io7m.looseleaf.tests/src/main/resources/com/io7m/looseleaf/tests/config.json
{
  "%schema": "https://www.io7m.com/software/looseleaf/looseleaf-config-1.json",

  "addresses": [
    {
      "host": "localhost",
      "port": 20000
    }
  ],

  "databaseFile": "/tmp/looseleaf.db",

  "roles": [
    {
      "name": "read-xy",
      "grants": [
        {
          "action": "READ",
          "keys": "/x/y/*"
        }
      ]
    },
    {
      "name": "write-xy",
      "grants": [
        {
          "action": "WRITE",
          "keys": "/x/y/*"
        }
      ]
    }
  ],

  "users": [
    {
      "name": "someone",
      "password": {
        "algorithm": "PBKDF2WithHmacSHA256:10000:256",
        "hash": "7706A5A86FEA0CE2BAC511FD0C3C10B3432D247CF28B8B9BD9CD99234D80B738",
        "salt": "4B4057CD69190E6D41898F9E793824D6"
      },
      "roles": [
        "read-xy", "write-xy"
      ]
    }
  ]
}
